### ISSUE TITLE
Extracting raw counts information

### ISSUE THREAD

**Issue by opplatek** [BitSeq/BitSeq#16]
Hi, 

I am running BitSeq-0.7.5 and I would like to extract information about estimated raw counts for each transcript. Help for BitSeq tells me it should be possible via $BitSeq/estimateVBExpression -o data -O counts data.prob but in the output I can see only theta etc. results. It works fine with $BitSeq/estimateVBExpression -o data -O RPKM data.prob to get the RPKM values but for raw counts nothing. I checked source code in estimateVBExpression.cpp and there is not section which would allow "counts" output. If you could explain this or point out the mistake I would be very grateful. 

Best, 
Jan

**Comment by mqbssppe** [comment]
Hi Jan,

The mean count of each transcript corresponds to the second column (alpha parameter of the dirichlet distribution) of the *.m_alphas output file of `estimateVBExpression` command. 

Best

Panos

**Comment by opplatek** [comment]
Hi Panos, 

Just to be sure - what do you mean by "mean count". This means count for each transcript averaged over some iterations? So if we would take it very generally - these "counts" could be taken as something similar as I would get from some other counting approaches for the transcripts?

Cheers, 
Jan

**Comment by mqbssppe** [comment]
Jan,

under the BitSeq model, the expression level of each transcript is described by a posterior distribution. Using the `estimateVBExpression` command, the posterior distribution is approximated by a Dirichlet distribution. The mean refers to the (estimated) mean of the marginal posterior distribution per transcript. 

You could also use the MCMC sampler, that is, `estimateExpression` command, which performs MCMC sampling from the posterior. In this case, the mean corresponds to the average across the MCMC iterations. Both methods will give you almost the same answer for the mean expression of each transcript (VB is significantly faster). 

You can interpret those estimates as the average count per transcript plus 1 (the constant term arises from the the fact that the prior distribution assigns 1 count per transcript). Thus, if you generate N samples from the posterior distribution, the mean count is just the average of the simulated values. And very generally speaking, it is essentially the same interpretation as the one from any other similar method (RSEM, etc..)

Panos

**Comment by opplatek** [comment]
Great! Thanks a lot.
