### ISSUE TITLE
parseAlignment caught segfault: address (nil), cause 'memory not mapped'

### ISSUE THREAD

**Issue by pimentel** [BitSeq/BitSeq#19]
Hi folks,

I am trying to run BitSeq on six samples at the same time (using `snakemake`). I wrote a simple Rscript that is called from the command line and then runs `getExpression`. I have also tried running it using `parallel::mclapply`. The same exact scripts run fine if they are in serial, but for some reason in parallel I get errors like this:

```
[time: +0.03 m]
[time: +0.03 m]
[time: +0.03 m]
[time: +0.03 m]

 *** caught segfault ***
address (nil), cause 'memory not mapped'

Traceback:
 1: .C("_parseAlignment", as.integer(argc), as.character(args))
 2: parseAlignment(alignFile, probF, trSeqFile, trInfoFile = trF,     uniform = uniform, limitA = limitA, expressionFile = exprFile,     pretend = pretend)
 3: getExpression(alignment_file, transcriptome, out, seed = seed)
 4: system.time(res <- getExpression(alignment_file, transcriptome,     out, seed = seed))
 5: eval(expr, envir, enclos)
 6: eval(ei, envir)
 7: withVisible(eval(ei, envir))
 8: source("BitSeq_getExpression.R")
aborting ...
[time: +0.03 m]
[time: +0.02 m]
Error in job BitSeq_expression while creating output files sims/gfr_3_3_20_42_2/exp_1/6/BitSeq.mean, sims/gfr_3_3_20_42_2/exp_1/6/BitSeq.prob, sims/gfr_3_3_20_42_2/exp_1/6/BitSeq.rpkm, sims/gfr_3_3_20_42_2/exp_1/6/BitSeq.thetaMeans, sims/gfr_3_3_20_42_2/exp_1/6/BitSeq.tr.
RuleException:
CalledProcessError in line 709 of /home/hjp/geuvadis/Snakefile:
Command 'Rscript --vanilla --default-packages=methods,stats,utils -e 'setwd("R")' -e 'source("BitSeq_getExpression.R")' ../sims/gfr_3_3_20_42_2/exp_1/6/bowtie.bam /home/hjp/annotation/Homo_sapiens.GRCh38.cdna.all.rel80.fa sims/gfr_3_3_20_42_2/exp_1/6/BitSeq' returned non-zero exit status -11
```

(this is output from snakemake). Have any of you experienced this?

Here is `BitSeq_getExpression.R`:

```r
args <- commandArgs(trailingOnly = TRUE)

if (length(args) != 3) {
  stop('Usage: Rscript BitSeq_getExpression.R BAM TRANSCRIPTOME_FA OUTPUT_PREFIX')
}

alignment_file <- args[1]
transcriptome <- args[2]
out <- args[3]

seed <- 42

suppressPackageStartupMessages(library('BitSeq'))

system.time(res <- getExpression(alignment_file, transcriptome, out,
  seed = seed))
```

Thank you,

Harold

**Comment by ahonkela** [comment]
Hi Harold,

Thanks for the report! I have not seen this before, but I have not tried anything similar either.

Based on your home directory I assume you are using Linux. The BitSeq R package uses OpenMP internally, which may be interfering with mclapply. OpenMP allows essentially perfect parallelisation for up to as many cores as there are MCMC chains (default: 4), so unless you have more cores mclapply will be essentially useless here. You can try disabling OpenMP by setting the environment variable OMP_NUM_THREADS=1 before running R, e.g. by using
 OMP_NUM_THREADS=1 Rscript ...
I am not sure if this will help with the crash, but at least it should simplify the resource allocation.

I also hope you are aware that there is a standalone version of BitSeq that can be easier to use for running things from the command line.

I will have a look if I can reproduce the issue and get back.


Antti

**Comment by magnusrattray** [comment]
Hi Harold,

Just to add to what Antti said I think the standalone version of BitSeq available from github is a better option is running direct from the command line since the R/Bioc version really just wraps the standalone code anyway. I'd also point out that we only use MCMC now if we are interested in the posterior variances. If you are just estimating the expression levels then the VB code is faster and gives pretty much identical results in our simulations. VB tends to underestimate the marginal posterior variance of expression which is why MCMC may still be of interest for differential expression studies using variance estimates. 

The BitSeq VB usage is explained here http://bitseq.github.io/howto/variationalBayes and the code for reproducing the benchmarks from our paper describing VB are here https://github.com/BitSeq/BitSeqVB_benchmarking/wiki

Magnus.

**Comment by pimentel** [comment]
Thank you both for the speedy reply!

@ahonkela I give the open mp environment variables a shot later today. I think I will probably try the commandline version first and see what happens. Just to be clear though, this also happens outside of using `mclapply` when I start several processes at the same time

@magnusrattray good to know. however, it seems that the variational bayes stuff is not compatible/advisable with DE?

Anyway, I will give the standalone version a try in a moment. Will report after.

**Comment by magnusrattray** [comment]
Correct, VB not advisable with DE methods that use technical variance currently (although we are thinking about ways to fix the variance in VB)

**Comment by pimentel** [comment]
All right...after quite a bit of futzing around, it turns out that there was some weird business going on with the machine. I'm not sure, but I think the alignment files were trashed. I reran everything and `parseAlignment` seems to be working correctly. Sorry for wasting your time with this.
