### ISSUE TITLE
Non uniform prior theta file format

### ISSUE THREAD

**Issue by zertan** [BitSeq/BitSeq#20]
Hi, I am using BitSeq to calculate proportions of reads mapping to different bacterial strains in a metagenomic sample (a problem closely resembling RNA transcript expression). I wonder if it is possible to use parseAlignment --uniform, then use BitSeqVB to estimate relative "transcript" (full bacterial genomes in my case) abundance and use this as new input to parseAlignment -e "Expression file" to get probabilities of each read/fragment mapping to each transcript? I just wonder what file format is "expression file"?

**Comment by magnusrattray** [comment]
Hi,

Did you mean to close this, did you resolve it? 

Magnus.

**Comment by zertan** [comment]
Hi,

No I thought it would perhaps be better to ask it in PROBIC/BIB pipeline. I am interested in resolving it.

Best regards,
Daniel

**Comment by magnusrattray** [comment]
Yes, BIB's the right place for this
