### ISSUE TITLE
ERROR: ArgumentParser: argument name phi unknown.

### ISSUE THREAD

**Issue by smb20200615** [BitSeq/BitSeq#23]
Hi,

Running this command (from https://github.com/PROBIC/BIB)
./BitSeq/estimateVBExpression -o abundance alignment_info.prob
gives the following error:

N mapped: 6617084
N total: 8910243
All alignments: 14131584
Isoforms: 18
End: bound decrease
iter(s): 4 bound: -185867736.563 grad: 0.0420366 beta: 0.0001973
ERROR: ArgumentParser: argument name phi unknown.
Do you know why this could be?

**Comment by ahonkela** [comment]
Thanks a lot for reporting!

This was a bug caused by previously added new feature, should be fixed now.

Please reopen the issue if the problem persists after updating to the latest version from the master branch!
