### ISSUE TITLE
gtftool include single-exon genes

### ISSUE THREAD

**Issue by Xinhuang1989** [BitSeq/BitSeq#24]
Thanks for having this wonderful package.

I am wondering if I can include single-exon genes when use gtftool to create pre-mRNA.fa?

Xin

**Comment by magnusrattray** [comment]
Hi, I think that in that case the pre-mRNA would be the same as the transcript and therefore there is no point including it in the transcript set. It will not cause an error but the inference will give equal probability to the pre-mRNA and mRNA transcripts and therefore it is not useful for inference.

**Comment by Xinhuang1989** [comment]
oh, it is useful when I create the reference if I analyze single nucleus RNA sequencing data or nascent mRNA data.

**Comment by magnusrattray** [comment]
Sorry, yes it is useful for genes with introns, I meant that I don't think the single exon ones are useful

**Comment by Xinhuang1989** [comment]
no worries, I will generate the whole pre-mRNA.fa by myself. Best!
